### ISSUE TITLE
Auction list issue *Bug*

### ISSUE THREAD

**Issue by arturek1666** [EpiCanard/GlobalMarketChest#87] opened 2019-06-27 09:06 UTC
Issue Goal :
*Bug*

Platform:
PaperSpigot 1.14.3

Plugin version :
1.3.0

Description :
It all started after I change version from 1.14.2 to 1.14.3, I had notice that auctions that are finished are counted in auction list:
![2019-06-26_21 08 57](https://user-images.githubusercontent.com/1558228/60252786-c2c0bf80-98c2-11e9-971b-3976054043a7.png)
![2019-06-26_21 08 59](https://user-images.githubusercontent.com/1558228/60252848-e421ab80-98c2-11e9-8645-7b1eb556fe9f.png)
I try to remove the shop and creating it again however I still have the same issue.

**Comment by EpiCanard** [comment] 2019-06-27 09:41
Oh ! It's a change from 1.14.2 to 1.14.3 ! Interesting.

If you undo auctions and create it again it fix the issue ?
It is only a graphical issue I will search what can cause this.

**Comment by arturek1666** [comment] 2019-06-27 09:45
I will try to remove the database and insert it back and I will see what will happen.

**Comment by arturek1666** [comment] 2019-06-27 09:49
I did remove all the auction placed it back again and I still have that issue somehow.

**Comment by EpiCanard** [comment] 2019-06-27 12:33
Thanks, I will see that soon :)

**Comment by EpiCanard** [comment] 2019-07-01 14:14
When you have remove auctions you have just made a backup of your database and restored it ?
Or you have removed auctions from shop and get back them in you inventory and then put them back inside shop ?

Because here the issue is the same than migration from 1.13 to 1.14, metadata of items changes. On the last interface I compare metadata of items to display the specific wanted item but if metadata had changed between versions it will not work :/

**Comment by arturek1666** [comment] 2019-07-01 19:59
I remove auctions by removing database and getting the backup as removing auction from shop for other players I don't know how.

**Comment by EpiCanard** [comment] 2019-07-01 23:33
Yes you only restore your database it will change nothing.
If you create a new auction with an item it will work normally.

It's an itemmeta serialization issue.

**Comment by EpiCanard** [comment] 2019-07-02 21:53
I will try to find a solution to fix this issue.

But if you want a quick solution, you can undo each auction,  get it back to your inventory and create again the auctions

**Comment by EpiCanard** [comment] 2019-07-10 21:29
I fixed the display issue. So if you had display issue between two versions now you will be able to see auctions and buy them.

The metadata has not been fixed so now if you have old auctions from previous version and auctions from new version you will see two two group of items that seems same.

I will try to create a command to fix this issue. But for now the actual fix allow to continue to buy auctions.

Version available on discord

**Comment by EpiCanard** [comment] 2019-07-10 21:37
[GlobalMarketChest-1.3.1-snapshot.zip](https://github.com/EpiCanard/GlobalMarketChest/files/3379473/GlobalMarketChest-1.3.1-snapshot.zip)

**Comment by arturek1666** [comment] 2019-07-13 07:13
Thx :) will check it out.

**Comment by EpiCanard** [comment] 2019-07-14 14:01
I added a new command `/globalmarketchest fix auctions [active | all]` to convert old auctions for new minecraft version.

The option is to define which auctions are changed :
- active : Only auction in progress or expired are update
- all: All auctions are update even auctions inside history

When auctions are converted the shop is locked and players can't use it, as long as auctions are not finished being updated. It should not take long time to convert. This security is to handle shop with a lot of auctions to convert, to prevent duplication issues :) 

This command will be inside next release

**Closed by EpiCanard** 2019-07-14 14:01 UTC
Labels: bug
