### ISSUE TITLE
Priority on load

### ISSUE THREAD

**Issue by Darkilen** [EpiCanard/GlobalMarketChest#66] opened 2019-04-02 12:44 UTC
Issue goal: Bug
Platform: Spigot 1.13.2
Plugin version: 1.1.0
Vault version: 1.7.1-b91

**Description**

With [AConomy](https://www.spigotmc.org/threads/aconomy-simple-vault-economy.358579/), GMC fail on load. It's apparently because he's loaded before AConomy.

More informations about priority [here](https://www.spigotmc.org/threads/priority-of-plugins.96841/)

_Issue reported by `Bobinho#0459` on Discord._

**Comment by EpiCanard** [comment] 2019-04-17 20:58
After testing with :
- Platform: Spigot 1.13.2
- Plugin version: 1.1.0
- Vault version: 1.7.1-b91
- Aconomy version: 2.1

It works perfectly, I can't reproduce the bug.
I close this issue, don't hesitate to reopen it if you still have this error @Bobinho#0459.

**Closed by EpiCanard** 2019-04-17 20:58 UTC
Labels: bug
